<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="AssemblyInfo.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Utils/Utils.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Configuration.fs" />
        <Compile Include="ChatTools.fs" />
        <Compile Include="Chat.fs" />
        <Compile Include="Structured.fs" />
        <Compile Include="ChatCommand.fs" />
    </ItemGroup>

    <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
