name: Check

on:
  #push:
  pull_request:
  schedule:
      -   cron:  '0 3 * * *'

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: macos-latest
            run: ./build.sh
          - name: ubuntu-latest
            run: ./build.sh
          - name: windows-latest
            run: ./build.cmd
        dotnet: [9.x]
    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore tools
        run: dotnet tool restore

      - name: Run tests
        run: ${{ matrix.os.run }}

  tests:
    strategy:
      matrix:
        os:
          - name: macos-latest
            run: ./build.sh
        dotnet: [9.x]
    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Run tests
        run: ${{ matrix.os.run }} -t tests
